Enums/EMailTemplate.cs

Just adding ParkingDisepensationRequest to the EMailTemplate

update(EMailTemplate) ParkingDispensationRequest

---

StockportGovUK.NetStandard.Models.csproj

update(csproj) update version to 1.0.2

---

Enums/EMailTemplate.cs

Hanged SpotsVenue to SportsVenue on enums

---

Models/Verint/Update/AddCaseFormFieldRequest.cs

merge add-case-form-field to develop

feat: Add verint AddCaseFormFieldRequest

---

Models/Booking/Request/AvailabilityRequest.cs
Models/Booking/Request/BookingRequest.cs
Models/Booking/Request/ConfirmationRequest.cs
Models/Booking/Response/AvailabilityDayResponse.cs
StockportGovUK.NetStandard.Models.csproj

﻿### Description
Fixed namespace for booking Request/Response models
Changed FulllDay property to IsFullDayAppointment

chore(booking): fixed namespace for booking models, changed FullDay property

---

Models/Booking/Request/AvailabilityRequest.cs
Models/Booking/Request/BookingRequest.cs
Models/Booking/Request/ConfirmationRequest.cs
Models/Booking/Response/AvailabilityDayResponse.cs
StockportGovUK.NetStandard.Models.csproj

Release 1.1.5
Includes:
Property rename on AvailabilityDayResponse model
Namespace fix for Booking models

build: release 1.1.5

---

Models/Booking/Response/AvailabilityDayResponse.cs

Added duration calculation on AppointmentTime

chore(Booking): Added duation calculation on AppointmentTime

---

Models/Booking/Request/BookingRequest.cs

Updated booking request model to replace Name with Firstname/Lastname and replace locatio with Address object

chore(booking): updated request to include Address and Firstname/Lastname

---

StockportGovUK.NetStandard.Models.csproj

chore(project): bump version

---

Models/Booking/Booking.cs

Added Endtime to booking model

chore(booking): Added booking endtime to model

---

Enums/EMailTemplate.cs
Models/BookSiteInspection/BookSiteInspectionMailModel.cs

Add Book site inspection mail model

feat(Book Site Inspection): add Book site inspection mail model

---

Models/BookSiteInspection/BookSiteInspectionMailModel.cs
StockportGovUK.NetStandard.Models.csproj

Update BookSiteInspection mail model to inherit from BaseMailModel

chore(Book Site Inspection): update model to inherit BaseMailModel

---

Models/Verint/Note.cs

Added empty constructor to allow for deserialization of object

fix(Case): Added empty constructor to Note

---

Enums/EAssetType.cs
Models/TrackAReport/Requests/TrackAReportRequest.cs
StockportGovUK.NetStandard.Models.csproj

* feat(TrackAReport): add model and enum class for TrackAReport
* refactor(TrackAReport): add Attributes

feat(TrackAReport): add model and enum class for TrackAReport (#93)

---

Models/TrackAReport/Requests/TrackAReportRequest.cs

Added email property to service, currently not required....

feat(poc_track-a_report_D-4751): add email

---

Models/TrackAReport/Requests/TrackAReportRequest.cs

fix(track_a_report): rm email

---

Models/TrackAReport/Requests/TrackAReportRequest.cs
StockportGovUK.NetStandard.Models.csproj

Removed email property from Track A Report Request Model

Release/patch 2.0.7

---

StockportGovUK.NetStandard.Models.csproj

fix(track_a_report_D-4751): version patch

---

Models/WasteDataService/AssistedCollection.cs
Models/WasteDataService/BaseBinType.cs
Models/WasteDataService/Bin.cs
Models/WasteDataService/BinRounds.cs
Models/WasteDataService/ContainedBy.cs
Models/WasteDataService/History.cs
Models/WasteDataService/Response/PropertyWasteData.cs

Added Response model for Waste data service

feat(waste): Models for property waste data response

---

Models/WasteDataService/AssistedCollection.cs
Models/WasteDataService/ContainedBy.cs
Models/WasteDataService/History.cs
Models/WasteDataService/Response/PropertyWasteData.cs
StockportGovUK.NetStandard.Models.csproj

- Updated waste data property types

feat: waste data model changes

---

Models/Booking/Booking.cs
StockportGovUK.NetStandard.Models.csproj

Includes:
- HashedId within booking model
- Booking Information Response

build: release 3.2.0

---

Models/Booking/Response/BookingInformationResponse.cs
StockportGovUK.NetStandard.Models.csproj

Enables case notes with attachment as part of case object for use on submission of case as well as after the fact.

Case notes with attachments, in Case object - Develop to Master

---

Models/Booking/Request/AvailabilityRequest.cs
StockportGovUK.NetStandard.Models.csproj

Adds extra property to availability request.

Availability request

---

Enums/EMailTemplate.cs
Models/StockportCanFund/StockportLocalFundMailModel.cs
StockportGovUK.NetStandard.Models.csproj

Add Stockport CAN Fund mail entity

feat(Stockport Can Fund): Add mail entity

---

Models/WasteDataService/Response/PropertyWasteData.cs

Added CalendarCode property to PropertyWasteData. Doesn't break anything

Calendar code

---

Models/BinCollection/Response/BinCollectionResponse.cs
StockportGovUK.NetStandard.Models.csproj

Added BinCollectionResponse Model

Bin collection response

---

Models/Uniform/HousingDisrepairServiceRequest.cs

fixed namespace error Model.Model

Housing disrepair

---

Models/Verint/Customer.cs

The library wouldn't deploy to nuget. This I assume is the cause

Fix customer

---

Models/WiredPlus/NewsletterSignUpRequest.cs
Models/WiredPlus/NewsletterSignUpResponse.cs
StockportGovUK.NetStandard.Models.csproj

feat(WiredPlus): minor add request/response models
